name: nasa_clean_arch
description: A new case study Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  http: ^0.13.5
  shimmer: ^2.0.0
  url_launcher: ^6.0.7
  youtube_player_iframe: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true